name: Publish cloud-utils-lib to GAR

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Auto bump version
        run: |
          python bump_version.py
          echo "VERSION=$(grep '^version' pyproject.toml | cut -d '"' -f2)" >> $GITHUB_ENV

      - name: Commit bumped version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump version to ${{ env.VERSION }}"
          branch: main

      - name: Authenticate to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: "projects/382207431122/locations/global/workloadIdentityPools/github-wif-999111/providers/github-provider"
          service_account: "github-oidc-sa@kxnwork.iam.gserviceaccount.com"

      - name: Install Python packaging tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine keyrings.google-artifactregistry-auth pytest

      - name: Clean dist folder
        run: rm -rf dist/*

      - name: Build wheel and sdist
        run: python -m build

      - name: Test package
        run: |
          pip install dist/*.whl
          pytest -q

      - name: Upload to Artifact Registry
        env:
          TWINE_REPOSITORY_URL: "https://us-central1-python.pkg.dev/kxnwork/python-cloud-utils/"
        run: |
          twine upload dist/*
